#!/usr/bin/env python3
"""
Gandalf's Configuration Wizard 🧙‍♂️
Interactive CLI setup for LOTR Data Cloud POC environment variables.
"""

import sys
import re
from datetime import datetime


def print_banner():
    """Print the wizard banner"""
    print("""
╔════════════════════════════════════════════════════════════╗
║  🧙‍♂️  GANDALF'S CONFIGURATION WIZARD  🧙‍♂️                   ║
║                                                            ║
║  "All we have to decide is what to do with the env        ║
║   vars that are given to us."                             ║
╚════════════════════════════════════════════════════════════╝

A wizard is never late, nor is he early.
He configures precisely what he means to.

Let us begin...
""")


def print_section(title):
    """Print a section header"""
    print(f"\n{title}")
    print("━" * len(title))


def validate_non_empty(value, field_name):
    """Validate that a value is non-empty"""
    if not value or not value.strip():
        return False, f"Gandalf senses emptiness. {field_name} cannot be empty."
    return True, None


def validate_url(value):
    """Validate that a value looks like a URL"""
    if not value.startswith("https://"):
        return False, "Gandalf senses deception in your URL format. Please use https://..."
    return True, None


def validate_api_name(value):
    """Validate that a value is a valid Salesforce API name"""
    if not re.match(r'^[a-zA-Z][a-zA-Z0-9_]*$', value):
        return False, "That name would not pass the gates of Moria. Use only letters, numbers, and underscores."
    return True, None


def get_input(prompt, default=None, validator=None):
    """
    Get user input with optional default and validation.
    Returns the validated input value.
    """
    while True:
        if default:
            user_input = input(f"{prompt} [{default}]: ").strip()
            if not user_input:
                user_input = default
        else:
            user_input = input(f"{prompt}: ").strip()
        
        if validator:
            valid, error = validator(user_input)
            if not valid:
                print(f"❌ {error}")
                print("   Please try again.\n")
                continue
        
        return user_input


def main():
    """Main wizard flow"""
    print_banner()
    
    # Collect configuration values
    config = {}
    
    # LOTR API Configuration
    print_section("🔑 LOTR API Configuration")
    print('"Speak, friend, and enter..."\n')
    
    config['LOTR_API_KEY'] = get_input(
        "Your LOTR API Key\n    (Get one at https://the-one-api.dev/sign-up)",
        validator=lambda v: validate_non_empty(v, "LOTR API Key")
    )
    
    # Data Cloud Configuration
    print_section("\n☁️  Salesforce Data Cloud Configuration")
    print('"You shall pass... credentials that is."\n')
    
    config['DATA_CLOUD_CLIENT_ID'] = get_input(
        "Data Cloud Client ID\n    (OAuth Connected App credentials)",
        validator=lambda v: validate_non_empty(v, "Client ID")
    )
    
    config['DATA_CLOUD_CLIENT_SECRET'] = get_input(
        "Data Cloud Client Secret",
        validator=lambda v: validate_non_empty(v, "Client Secret")
    )
    
    config['DATA_CLOUD_AUTH_URL'] = get_input(
        "Data Cloud Auth URL",
        default="https://login.salesforce.com",
        validator=validate_url
    )
    
    config['DATA_CLOUD_INGESTION_URL'] = get_input(
        "Data Cloud Ingestion API URL\n    (e.g., https://your-instance.my.salesforce.com)",
        validator=validate_url
    )
    
    # Ingestion Source Configuration
    print_section("\n📦 Data Cloud Ingestion Source Configuration")
    print('"One does not simply... skip the metadata setup."\n')
    
    config['DATA_CLOUD_SOURCE_NAME'] = get_input(
        "Source API Name",
        default="lotr_characters",
        validator=validate_api_name
    )
    
    config['DATA_CLOUD_OBJECT_NAME'] = get_input(
        "Object API Name",
        default="LotrCharacter",
        validator=validate_api_name
    )
    
    # Validation
    print("\n✨ Validating your configuration...")
    print('"Even the smallest config can change the course of the future."')
    
    # All validations passed during input
    print("\n✅ All checks passed!")
    
    # Write .env file
    print("\nWriting configuration to .env file...")
    
    env_content = f"""# LOTR Data Cloud POC Configuration
# Generated by Gandalf on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

# The One API
LOTR_API_KEY={config['LOTR_API_KEY']}

# Salesforce Data Cloud OAuth
DATA_CLOUD_CLIENT_ID={config['DATA_CLOUD_CLIENT_ID']}
DATA_CLOUD_CLIENT_SECRET={config['DATA_CLOUD_CLIENT_SECRET']}
DATA_CLOUD_AUTH_URL={config['DATA_CLOUD_AUTH_URL']}

# Ingestion API
DATA_CLOUD_INGESTION_URL={config['DATA_CLOUD_INGESTION_URL']}
DATA_CLOUD_SOURCE_NAME={config['DATA_CLOUD_SOURCE_NAME']}
DATA_CLOUD_OBJECT_NAME={config['DATA_CLOUD_OBJECT_NAME']}
"""
    
    try:
        with open('.env', 'w') as f:
            f.write(env_content)
        
        # Update .gitignore
        gitignore_path = '.gitignore'
        try:
            with open(gitignore_path, 'r') as f:
                gitignore_content = f.read()
            
            if '.env' not in gitignore_content:
                with open(gitignore_path, 'a') as f:
                    if not gitignore_content.endswith('\n'):
                        f.write('\n')
                    f.write('.env\n')
        except FileNotFoundError:
            # Create .gitignore if it doesn't exist
            with open(gitignore_path, 'w') as f:
                f.write('.env\n')
        
        print("""
🎉 The beacons of Minas Tirith are lit!
   Your .env file is ready.

⚠️  IMPORTANT: Keep your .env file secret! It contains the keys to Mordor.
   (It has been added to .gitignore)

You may now run:
  python app.py

Fly, you fools! 🚀
""")
        
    except Exception as e:
        print(f"\n❌ Error writing configuration: {e}")
        print("The shadow grows... but fear not, try again.")
        sys.exit(1)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n👋 The Grey Pilgrim departs. Farewell!")
        sys.exit(0)

